### PR TITLE
Remove the Scala plugin

### PR DESCRIPTION
**Pull request by jackkoenig**
This has been moved to api-scala-sifive: https://github.com/sifive/api-scala-sifive/pull/27

### CODE REVIEW

**Comment by mmjconolly** [comment]
nit: `complete.bash` has some references to scala plugin

**Comment by jackkoenig** [comment]
Nice catch, fixed

**Comment by jackkoenig** [comment]
CI is soooo much faster now 🙂

**Comment by richardxia** [comment]
> CI is soooo much faster now 🙂

It looks like the slowest part is now building the Dockerfile for the wit action. I bet I could make this faster by pulling down the previously built image and then building on top of that :P.

**Pull request merged**
